/**
 * 🔄 TIPOS DE ERROR UNIFICADOS - API01 & SIU01 COMPATIBLE
 *
 * ✅ Retrocompatible con ambos componentes
 * ✅ Sincronizado entre proyectos
 * ✅ Tipos adicionales para sistema de asistencia
 * ✅ Duplicados/redundancias consolidados
 *
 * Última actualización: 2024-12-19
 */

export enum RequestErrorTypes {
  INVALID_PARAMETERS = "INVALID_PARAMETERS",
  MISSING_PARAMETERS = "MISSING_PARAMETERS",
  REQUEST_FAILED = "REQUEST_FAILED",
  MALFORMED_REQUEST = "MALFORMED_REQUEST",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
}

export enum TokenErrorTypes {
  TOKEN_UNAUTHORIZED = "TOKEN_UNAUTHORIZED",
  TOKEN_MISSING = "TOKEN_MISSING",
  TOKEN_INVALID_FORMAT = "TOKEN_INVALID_FORMAT",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_MALFORMED = "TOKEN_MALFORMED",
  TOKEN_INVALID_SIGNATURE = "TOKEN_INVALID_SIGNATURE",
  TOKEN_WRONG_ROLE = "TOKEN_WRONG_ROLE",
  TOKEN_REVOKED = "TOKEN_REVOKED",
  TOKEN_NOT_ACTIVE_YET = "TOKEN_NOT_ACTIVE_YET",
}

export enum UserErrorTypes {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_INACTIVE = "USER_INACTIVE",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_ROLE_MISMATCH = "USER_ROLE_MISMATCH",
  USER_SUSPENDED = "USER_SUSPENDED",
  USER_DELETED = "USER_DELETED",
}

export enum PermissionErrorTypes {
  ROLE_BLOCKED = "ROLE_BLOCKED",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  PERMISSION_DENIED = "PERMISSION_DENIED",
}

export enum SystemErrorTypes {
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  SERVER_ERROR = "SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  MAINTENANCE_MODE = "MAINTENANCE_MODE",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
}

export enum ValidationErrorTypes {
  INVALID_USER_IDENTIFIER = "INVALID_USER_IDENTIFIER",
  INVALID_GENDER = "INVALID_GENDER",
  INVALID_PHONE = "INVALID_PHONE",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_USERNAME = "INVALID_USERNAME",
  INVALID_NAME = "INVALID_NAME",
  INVALID_LASTNAME = "INVALID_LASTNAME",
  STRING_TOO_LONG = "STRING_TOO_LONG",
  FIELD_REQUIRED = "FIELD_REQUIRED", // ✅ Se elimina REQUIRED_FIELDS (duplicado)
  INVALID_FORMAT = "INVALID_FORMAT",
  ROLE_NOT_ALLOWED = "ROLE_NOT_ALLOWED",
  INVALID_REFERENCE = "INVALID_REFERENCE",
  VALUE_ALREADY_EXISTS = "VALUE_ALREADY_EXISTS",
  INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT",
  DATE_OUT_OF_RANGE = "DATE_OUT_OF_RANGE",
  INVALID_TIME_FORMAT = "INVALID_TIME_FORMAT",
  INVALID_ENUM_VALUE = "INVALID_ENUM_VALUE",
}

export enum DataConflictErrorTypes {
  VALUE_ALREADY_IN_USE = "CONFLICTO_VALOR_YA_EN_USO",
  RELATED_DATA_EXISTS = "CONFLICTO_DATOS_RELACIONADOS_EXISTEN",
  DATABASE_CONSTRAINT = "CONFLICTO_RESTRICCIÓN_BASE_DATOS",
  CONCURRENT_MODIFICATION = "CONFLICTO_MODIFICACIÓN_CONCURRENTE",
  VERSION_MISMATCH = "CONFLICTO_VERSIÓN_NO_COINCIDE",
  DEPENDENCY_EXISTS = "CONFLICTO_DEPENDENCIA_EXISTE",
  // ✅ Se elimina RECORD_NOT_FOUND: no es un conflicto, ya existe en DataErrorTypes
}

export enum FileErrorTypes {
  FILE_MISSING = "FILE_MISSING",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED",
  FILE_DELETE_FAILED = "FILE_DELETE_FAILED",
  FILE_CORRUPTED = "FILE_CORRUPTED",
  FILE_PROCESSING_FAILED = "FILE_PROCESSING_FAILED",
  INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE",
}

export enum AuthenticationErrorTypes {
  MAX_ATTEMPTS_EXCEEDED = "MAX_ATTEMPTS_EXCEEDED",
  VERIFICATION_FAILED = "VERIFICATION_FAILED",
  CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED",
  OTP_INVALID = "OTP_INVALID",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  TEMPORARY_BLOCKED = "TEMPORARY_BLOCKED",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_ALREADY_USED = "OTP_ALREADY_USED",
  AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED",
}

export enum DataErrorTypes {
  RECORD_NOT_FOUND = "RECORD_NOT_FOUND", // ✅ Único punto de verdad para "registro no encontrado"
  NO_DATA_AVAILABLE = "NO_DATA_AVAILABLE",
  DATA_NOT_EXISTS = "DATA_NOT_EXISTS",
  INVALID_DATA_FORMAT = "INVALID_DATA_FORMAT",
  DATA_CORRUPTED = "DATA_CORRUPTED",
  DATA_INCONSISTENT = "DATA_INCONSISTENT",
}

export enum NetworkErrorTypes {
  NETWORK_ERROR = "NETWORK_ERROR",
  CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT", // ✅ Se elimina TIMEOUT_ERROR (duplicado)
  CONNECTION_REFUSED = "CONNECTION_REFUSED",
  DNS_ERROR = "DNS_ERROR",
  OFFLINE = "OFFLINE",
  POOR_CONNECTION = "POOR_CONNECTION",
}

export enum SyncErrorTypes {
  SYNC_ERROR = "SYNC_ERROR",
  SYNC_CONFLICT = "SYNC_CONFLICT",
  SYNC_TIMEOUT = "SYNC_TIMEOUT",
  SYNC_FAILED = "SYNC_FAILED",
  SYNC_INTERRUPTED = "SYNC_INTERRUPTED",
  SYNC_DATA_MISMATCH = "SYNC_DATA_MISMATCH",
}

export enum CacheErrorTypes {
  CACHE_ERROR = "CACHE_ERROR",
  CACHE_MISS = "CACHE_MISS",
  CACHE_EXPIRED = "CACHE_EXPIRED",
  CACHE_CORRUPTED = "CACHE_CORRUPTED",
  CACHE_FULL = "CACHE_FULL",
  CACHE_UNAVAILABLE = "CACHE_UNAVAILABLE",
}

export enum StorageErrorTypes {
  STORAGE_FULL = "STORAGE_FULL",
  STORAGE_ERROR = "STORAGE_ERROR",
  STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE",
  STORAGE_CORRUPTED = "STORAGE_CORRUPTED",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",
  INDEXEDDB_ERROR = "INDEXEDDB_ERROR",
}

export enum AttendanceErrorTypes {
  ATTENDANCE_ALREADY_MARKED = "ATTENDANCE_ALREADY_MARKED",
  ATTENDANCE_WINDOW_CLOSED = "ATTENDANCE_WINDOW_CLOSED",
  INVALID_ATTENDANCE_TIME = "INVALID_ATTENDANCE_TIME",
  ATTENDANCE_NOT_FOUND = "ATTENDANCE_NOT_FOUND",
  ATTENDANCE_LOCKED = "ATTENDANCE_LOCKED",
  SCHEDULE_CONFLICT = "SCHEDULE_CONFLICT",
}

type AllErrorTypes =
  | RequestErrorTypes
  | TokenErrorTypes
  | UserErrorTypes
  | PermissionErrorTypes
  | SystemErrorTypes
  | ValidationErrorTypes
  | DataConflictErrorTypes
  | FileErrorTypes
  | DataErrorTypes
  | AuthenticationErrorTypes
  | NetworkErrorTypes
  | SyncErrorTypes
  | CacheErrorTypes
  | StorageErrorTypes
  | AttendanceErrorTypes;

export default AllErrorTypes;