
// DURACION DE LOS TOKEN JWT PARA CADA TIPO DE USUARIO

export const ADMINISTRADORES_SESSION_EXPIRATION = 60 * 60 * 12;      // 12 horas
export const CUENTAS_TEMPORALES_SESSION_EXPIRATION = 60 * 60 * 12;   // 12 horas

